# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-11 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('emr', '0164_auto_20190212_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coloncancerscreening',
            name='last_risk_updated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coloncancerstudy',
            name='last_updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='coloncancerstudy',
            name='study_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='inr',
            name='next_inr',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='problemsegment',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='todo',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usertelecom',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usertelecom',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
