# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-09-21 14:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0167_encountermedication_vwmedications_vwproblems_vwtoppatients'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneBmiPerEncounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='encounter_bmi', to='emr.Encounter')),
            ],
            options={
                'db_table': 'emr_one_bmi_per_encounter',
            },
        ),
    ]
