# Generated by Django 5.1.2 on 2026-05-06 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0167_encountermedication_vwmedications_vwproblems_vwtoppatients'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnomedConcept',
            fields=[
                ('concept_id', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='coloncancerscreening',
            name='risk',
            field=models.CharField(choices=[('normal', 'Normal'), ('high', 'High')], default='normal', max_length=10),
        ),
        migrations.AlterField(
            model_name='coloncancerstudyimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='studies/'),
        ),
        migrations.AlterField(
            model_name='commonproblem',
            name='problem_type',
            field=models.CharField(choices=[('acute', 'Acute'), ('chronic', 'Chronic')], default='acute', max_length=10),
        ),
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='recorder_status',
            field=models.IntegerField(choices=[(0, 'isRecording'), (1, 'isPaused'), (2, 'isStopped')], default=0),
        ),
        migrations.AlterField(
            model_name='encounterevent',
            name='summary',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='observation',
            name='graph',
            field=models.TextField(default='Line'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='problem',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='problem',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='problemnote',
            name='note_type',
            field=models.CharField(choices=[('wiki', 'Wiki'), ('history', 'History')], max_length=50),
        ),
        migrations.AlterField(
            model_name='taggedtodoorder',
            name='status',
            field=models.IntegerField(choices=[(0, 'New'), (1, 'Seen'), (2, 'Viewed')], default=0),
        ),
        migrations.AlterField(
            model_name='textnote',
            name='by',
            field=models.CharField(choices=[('patient', 'patient'), ('physician', 'physician')], max_length=20),
        ),
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.PositiveIntegerField(choices=[(0, ''), (1, 'inr_widget')], default=0),
        ),
        migrations.AlterField(
            model_name='todoattachment',
            name='attachment',
            field=models.FileField(blank=True, upload_to='attachments/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cover_image',
            field=models.ImageField(default='/static/images/cover.png', upload_to='cover_image/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='inr_target',
            field=models.PositiveIntegerField(choices=[(1, '2-3'), (0, '2.5-3.5')], default=1),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='portrait_image',
            field=models.ImageField(default='/static/images/avatar.png', upload_to='cover_image/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('patient', 'Patient'), ('physician', 'Physician'), ('mid-level', 'Mid Level PA/NP'), ('nurse', 'Nurse'), ('secretary', 'Secretary'), ('admin', 'Admin')], default='patient', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=6),
        ),
        migrations.AlterModelTable(
            name='vwproblems',
            table='vw_problems_full',
        ),
        migrations.CreateModel(
            name='SnomedRelationship',
            fields=[
                ('id', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('type_id', models.CharField(max_length=18)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='emr.snomedconcept')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='emr.snomedconcept')),
            ],
        ),
    ]
