# Generated by Django 5.1.2 on 2026-05-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0168_snomedconcept_alter_coloncancerscreening_risk_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnomedIcd10Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snomed_concept_id', models.CharField(db_index=True, max_length=18)),
                ('icd10_code', models.CharField(max_length=15)),
                ('map_advice', models.TextField(blank=True, null=True)),
                ('map_group', models.IntegerField(default=1)),
                ('map_priority', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['map_group', 'map_priority'],
                'unique_together': {('snomed_concept_id', 'icd10_code', 'map_group', 'map_priority')},
            },
        ),
    ]
