# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-09-21 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0168_onebmiperencounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='bmi_updated_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='onebmiperencounter',
            table=None,
        ),
    ]
