# Generated by Django 5.1.2 on 2026-05-14 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0169_add_snomed_icd10_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='icd10_code',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
