# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-09-21 14:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0169_auto_20210921_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onebmiperencounter',
            name='encounter',
        ),
        migrations.DeleteModel(
            name='OneBmiPerEncounter',
        ),
    ]
