# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-09-27 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0170_auto_20210921_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encounter',
            name='bmi_updated_count',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='weigth_updated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
