# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-09-28 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0172_auto_20210927_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='height_changed_first_time',
            field=models.BooleanField(default=False),
        ),
    ]
