# Generated by Django 5.1.2 on 2026-06-08 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0172_encounter_client_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemactivity',
            name='problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emr.problem'),
        ),
    ]
