# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-09-28 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0173_userprofile_height_changed_first_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='height_updated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
