# Generated by Django 5.1.2 on 2026-06-09 01:13

import emr.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0174_patient_image_pr2_columns_and_uuid_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='client_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(null=True, upload_to=emr.models.set_document_path_uuid),
        ),
    ]
