# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2022-05-02 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0174_userprofile_height_updated_date'),
    ]

    operations = [
    ]