# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2022-06-15 14:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0175_auto_20220502_1532'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='vwproblems',
            table='vw_problems_full',
        ),
    ]
