# Generated by Django 4.2.3 on 2023-11-01 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('emr', '0176_auto_20220615_0800')]

    operations = [
        migrations.AlterField(
            model_name="DocumentTodo",
            name="document",
            field=models.ForeignKey(
                to="Document", null=True, on_delete=models.SET_NULL
            ),
        )
    ]
