# Generated by Django 4.2.3 on 2023-11-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emr", "0177_auto_20231101_1415"),
    ]

    operations = [ 
        migrations.AlterField(
            model_name="EncounterObservationValue",
            name="encounter",
            field=models.ForeignKey(
                to="Encounter", null=True, on_delete=models.SET_NULL
            ),
        ),
        migrations.AlterField(
            model_name="EncounterObservationValue",
            name="observation_value",
            field=models.ForeignKey(
                to="ObservationValue", null=True, on_delete=models.SET_NULL
            ),
        )
    ]
