# Generated by Django 5.1.2 on 2026-06-24 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0178_userprofile_provider_practice_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemnote',
            name='client_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
