# Generated by Django 4.2.3 on 2023-11-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emr", "0178_auto_20231102_1330"),
    ]

    operations = [
        migrations.AlterField(
            model_name="EncounterProblemRecord",
            name="encounter",
            field=models.ForeignKey(
                to="Encounter", null=True, on_delete=models.SET_NULL
            ),
        ),
        migrations.AlterField(
            model_name="EncounterProblemRecord",
            name="problem",
            field=models.ForeignKey(
                to="Problem", null=True, on_delete=models.SET_NULL
            ),
        )
    ]
