# Generated by Django 4.2.3 on 2023-11-02 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emr", "0179_auto_20231102_1337"),
    ]

    operations = [
        migrations.AlterField(
            model_name="EncounterTodoRecord",
            name="encounter",
            field=models.ForeignKey(
                to="Encounter", null=True, on_delete=models.SET_NULL
            ),
        ),
        migrations.AlterField(
            model_name="EncounterTodoRecord",
            name="todo",
            field=models.ForeignKey(
                to="ToDo", null=True, on_delete=models.SET_NULL
            ),
        )
    ]
