# Generated by Django 5.1.2 on 2026-07-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0180_patientmutationstamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='client_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
