# Generated by Django 4.2.14 on 2024-07-23 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0180_auto_20231102_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coloncancerscreening',
            name='risk',
            field=models.CharField(choices=[('normal', 'Normal'), ('high', 'High')], default='normal', max_length=10),
        ),
        migrations.AlterField(
            model_name='coloncancerstudyimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='studies/'),
        ),
        migrations.AlterField(
            model_name='commonproblem',
            name='problem_type',
            field=models.CharField(choices=[('acute', 'Acute'), ('chronic', 'Chronic')], default='acute', max_length=10),
        ),
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='documenttodo',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='emr.document'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='recorder_status',
            field=models.IntegerField(choices=[(0, 'isRecording'), (1, 'isPaused'), (2, 'isStopped')], default=0),
        ),
        migrations.AlterField(
            model_name='encounterevent',
            name='encounter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encounter_events', to='emr.encounter'),
        ),
        migrations.AlterField(
            model_name='encounterevent',
            name='summary',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='encountermedication',
            name='encounter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='medications', to='emr.encounter'),
        ),
        migrations.AlterField(
            model_name='encountermedication',
            name='medication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='encounters', to='emr.medication'),
        ),
        migrations.AlterField(
            model_name='encounterobservationvalue',
            name='encounter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='emr.encounter'),
        ),
        migrations.AlterField(
            model_name='encounterobservationvalue',
            name='observation_value',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='emr.observationvalue'),
        ),
        migrations.AlterField(
            model_name='encounterproblemrecord',
            name='encounter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encounter_problem_records', to='emr.encounter'),
        ),
        migrations.AlterField(
            model_name='encounterproblemrecord',
            name='problem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problem_encounter_records', to='emr.problem'),
        ),
        migrations.AlterField(
            model_name='encountertodorecord',
            name='encounter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encounter_todo_records', to='emr.encounter'),
        ),
        migrations.AlterField(
            model_name='encountertodorecord',
            name='todo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='todo_encounter_records', to='emr.todo'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='graph',
            field=models.TextField(default='Line'),
        ),
        migrations.AlterField(
            model_name='observationunit',
            name='observation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observation_units', to='emr.observation'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='problem',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='problem',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='problemnote',
            name='note_type',
            field=models.CharField(choices=[('wiki', 'Wiki'), ('history', 'History')], max_length=50),
        ),
        migrations.AlterField(
            model_name='taggedtodoorder',
            name='status',
            field=models.IntegerField(choices=[(0, 'New'), (1, 'Seen'), (2, 'Viewed')], default=0),
        ),
        migrations.AlterField(
            model_name='textnote',
            name='by',
            field=models.CharField(choices=[('patient', 'patient'), ('physician', 'physician')], max_length=20),
        ),
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.PositiveIntegerField(choices=[(0, ''), (1, 'inr_widget')], default=0),
        ),
        migrations.AlterField(
            model_name='todoattachment',
            name='attachment',
            field=models.FileField(blank=True, upload_to='attachments/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cover_image',
            field=models.ImageField(default='/static/images/cover.png', upload_to='cover_image/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='inr_target',
            field=models.PositiveIntegerField(choices=[(1, '2-3'), (0, '2.5-3.5')], default=1),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='portrait_image',
            field=models.ImageField(default='/static/images/avatar.png', upload_to='cover_image/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('patient', 'Patient'), ('physician', 'Physician'), ('mid-level', 'Mid Level PA/NP'), ('nurse', 'Nurse'), ('secretary', 'Secretary'), ('admin', 'Admin')], default='patient', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=6),
        ),
        migrations.AlterModelTable(
            name='vwproblems',
            table='vw_problems_full',
        ),
    ]
