# Generated by Django 4.2.14 on 2024-07-26 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0181_alter_coloncancerscreening_risk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='observationvalue',
            name='note',
            field=models.TextField(blank=True, max_length=128, null=True),
        ),
    ]
