# Generated by Django 5.1.15 on 2026-07-22 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0183_repair_join_table_null_drift'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='client_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
