# Generated by Django 5.1.15 on 2026-07-24 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0185_backfill_patient_controllers'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
