# Generated by Django 5.1.15 on 2026-08-17 21:40
#
# Document full-text index columns. All three are nullable with no default,
# so MySQL 8 applies them INSTANT — no table rebuild on the ~59k-row Document
# table, and the migration is safe to run on container boot the way
# init-cloudrun.sh does. NULL means "never extracted"; see
# emr.Document.extracted_text for why empty string is a distinct state.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0186_document_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='extracted_text_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='extracted_text_version',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
