# Generated by Django 5.1.15 on 2026-08-26 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0188_label_snomed_category_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='audio_end_offset',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
