# Generated by Django 5.1.15 on 2026-09-17 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0189_encounter_audio_end_offset'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservationValueAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_id_snapshot', models.IntegerField()),
                ('observation_code', models.CharField(blank=True, default='', max_length=10)),
                ('observation_name', models.CharField(blank=True, default='', max_length=255)),
                ('component_id_snapshot', models.IntegerField(blank=True, null=True)),
                ('value_id_snapshot', models.IntegerField(db_index=True)),
                ('client_uuid', models.UUIDField(blank=True, null=True)),
                ('action', models.CharField(choices=[('edited', 'Edited'), ('deleted', 'Deleted')], max_length=8)),
                ('old_quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('new_quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('old_unit', models.CharField(blank=True, default='', max_length=45)),
                ('new_unit', models.CharField(blank=True, default='', max_length=45)),
                ('old_effective_datetime', models.DateTimeField(blank=True, null=True)),
                ('new_effective_datetime', models.DateTimeField(blank=True, null=True)),
                ('original_author_name', models.CharField(blank=True, default='', max_length=255)),
                ('actor_name', models.CharField(blank=True, default='', max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('original_author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observation_value_audits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
                'indexes': [models.Index(fields=['patient', 'action'], name='emr_ovaudit_patient_action'), models.Index(fields=['patient', 'observation_code'], name='emr_ovaudit_patient_code')],
            },
        ),
    ]
