# Generated by Django 5.1.15 on 2026-10-07 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0192_observationpinoptout'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EncounterTranscriptTiming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('timed', 'Timed'), ('silent', 'Silent'), ('no_audio', 'No audio')], default='timed', max_length=16)),
                ('format_version', models.PositiveSmallIntegerField(default=1)),
                ('transcript_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('payload', models.TextField(blank=True, default='')),
                ('audio_duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('engine', models.CharField(blank=True, default='', max_length=120)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('encounter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transcript_timing', to='emr.encounter')),
            ],
        ),
    ]
