# Generated by Django 4.2.14 on 2024-07-23 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pain', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PainAvatar',
        ),
    ]
