python /var/www/foundation/manage.py cron review_colorectal_cancer_risk_assessment
python /var/www/foundation/manage.py cron patient_needs_a_plan_for_colorectal_cancer_screening
python /var/www/foundation/manage.py cron observation_order_was_automatically_generated